# .github/workflows/python-app.yml
name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov pylint
    - name: Lint with pylint
      run: |
        pylint --disable=C0111,C0103,R0903 app tests
    - name: Test with pytest
      run: |
        pytest --cov=app tests/
    - name: Check test coverage
      run: |
        python -m pytest --cov=app --cov-report=term-missing --cov-fail-under=90 tests/