# .github/workflows/python-app.yml
name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov pylint

    - name: Check file structure (Debugging Step)
      run: |
        echo "Project Structure:"
        ls -R

    - name: Run Pylint
      run: |
        pylint app tests --disable=C0111,C0103,R0903,C0114,C0115,C0116,W0621,C0301,R0913,R0914,W0702,C0305,W1203,W0718,W0707,C0303,C0415,R1705,W0611,W0107,W0105,W0221,W0212,R0801

    - name: Run Pytest
      run: |
        if [ -d "tests" ]; then
          python -m pytest --cov=app/commands/ --cov-report=term-missing --cov-fail-under=50 tests/
        else
          echo "Error: 'tests/' directory not found"
          exit 1
        fi
